
apiVersion: v1
kind: Service
metadata:
  name: kubebox
  labels:
    template: kubebox
  namespace: $NAMESPACE
spec:
  ports:
    - name: kubebox
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: kubebox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubebox
  namespace: $NAMESPACE
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: kubebox
  template:
    metadata:
      name: kubebox
      labels:
        name: kubebox
    spec:
      serviceAccountName: kubebox
      containers:
      - image: astefanutti/kubebox:server
        imagePullPolicy: Always
        name: kubebox
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubebox
  namespace: $NAMESPACE
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubebox
  namespace: $NAMESPACE
subjects:
- kind: ServiceAccount
  name: kubebox
  namespace: $NAMESPACE
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubebox
  namespace: $NAMESPACE
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list